In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

In [2]:
db_url = "postgresql+psycopg2://student:qweasd963@95.163.241.236:5432/analytics_lab"
engine = create_engine(db_url)

In [3]:
passengers = pd.read_sql('SELECT * FROM cityride.passengers', engine)

In [4]:
drivers = pd.read_sql('SELECT * FROM cityride.drivers', engine)

In [5]:
rides = pd.read_sql('SELECT * FROM cityride.rides', engine)

In [42]:
rides['req_date'] = pd.to_datetime(rides['request_time']).dt.date
rides['req_dayw'] = pd.to_datetime(rides['request_time']).dt.day_name()
rides['req_hour'] = pd.to_datetime(rides['request_time']).dt.hour

In [30]:
rides['req_week'] = rides['request_time'].dt.isocalendar().week

In [60]:
## Функция определения времени дня заказа
def time_of_day (time):
    if time >= 6 and time < 11.5:
        return '1_morning'
    elif (time >= 11.5) and (time < 16.5):
        return '2_daytime'
    elif (time >= 16.5) and (time < 22):
        return '3_evening'
    else:
        return '4_night'

In [61]:
rides['time_of_day'] = rides['req_hour'].apply(time_of_day)

In [63]:
rides.head(3)

,ride_id,passenger_id,driver_id,request_time,pickup_time,dropoff_time,pickup_address,dropoff_address,pickup_lat,pickup_lon,...,fare_amount,status,cancellation_reason,ab_test_variant,req_date,req_dayw,req_hour,req_week,time_of_day,district_name
0,1,1802,61,2024-07-03 16:51:00,2024-07-03 16:59:00,2024-07-03 17:12:00,"Казань, Ново-Савиновский р-н, ул. Примерная, 153","Казань, Центр р-н, ул. Другая, 163",55.753447,49.150420,...,259.75,completed,None,A,2024-07-03,Wednesday,16,27,2_daytime,Ново-Савиновский
1,2,967,142,2024-08-02 11:28:00,2024-08-02 11:31:00,2024-08-02 11:39:00,"Казань, Советский р-н, ул. Примерная, 167","Казань, Приволжский р-н, ул. Другая, 168",55.809708,49.046326,...,215.72,completed,None,A,2024-08-02,Friday,11,31,1_morning,Советский
2,3,953,69,2024-10-12 18:15:00,2024-10-12 18:19:00,2024-10-12 18:44:00,"Казань, Советский р-н, ул. Примерная, 86","Казань, Центр р-н, ул. Другая, 33",55.835653,49.076059,...,353.39,completed,None,B,2024-10-12,Saturday,18,41,3_evening,Советский

In [7]:
today = '2024-03-08'
ts = pd.to_datetime(today)
dt = ts.date()
type(dt)

datetime.date

In [24]:
kpi_daily = pd.DataFrame({'cnt_ord' : [rides[rides['req_date'] == dt]['ride_id'].count()], \
                          'cnt_compl' : [rides[(rides['req_date'] == dt) & (rides['status'] == 'completed')]['ride_id'].count()],\
                          'gmv' : [rides[rides['req_date'] == dt]['fare_amount'].sum()],\
                          'avg_sum' : [rides[rides['req_date'] == dt]['fare_amount'].sum()/ \
                          rides[(rides['req_date'] == dt) & (rides['status'] == 'completed')]['ride_id'].count()],
                          'avg_distance' : [rides[rides['req_date'] == dt]['distance_km'].mean()],
                          'avg_duration' : [rides[rides['req_date'] == dt]['duration_minutes'].mean()],
                          'compl_rate' : [rides[(rides['req_date'] == dt) & (rides['status'] == 'completed')]['ride_id'].count() / \
                                          rides[rides['req_date'] == dt]['ride_id'].count()]
                         })
print(kpi_daily)

   cnt_ord  cnt_compl       gmv     avg_sum  avg_distance  avg_duration  \
0      130        129  46292.03  358.852946      6.042713     20.666667

   compl_rate
0    0.992308

In [21]:
kpi_daily_2 = rides.groupby('req_date').agg(
                                            rides_count = ('ride_id', 'count'),
                                            gmv = ('fare_amount', 'sum'),           # GMV
                                            avg_fare = ('fare_amount', 'mean'),           # avg fare
                                            avg_distance = ('distance_km', 'mean'),          # avg distance
                                            avg_duration = ('duration_minutes', 'mean'),        # avg duration
                                            completion_rate = ('status', lambda x: (x == 'completed').mean())  # completion rate
                                            ).reset_index()
kpi_daily_2[kpi_daily_2['req_date'] == dt]

,req_date,rides_count,gmv,avg_fare,avg_distance,avg_duration,completion_rate
67,2024-03-08,130,46292.03,358.852946,6.042713,20.666667,0.992308

In [64]:
rides_time_series_day = rides.groupby(['req_date', 'time_of_day']).agg({
'ride_id': 'count',
'fare_amount': ['sum', 'mean']
}).reset_index()
rides_time_series_day.columns = ['date', 'time_of_day', 'rides_count', 'gmv', 'avg_fare']
rides_time_series_day.head()

         date time_of_day  rides_count       gmv    avg_fare
0  2024-01-01   1_morning           36  12471.07  356.316286
1  2024-01-01   2_daytime           34  11753.65  367.301562
2  2024-01-01   3_evening           49  17954.05  374.042708
3  2024-01-01     4_night           13   4650.20  357.707692
4  2024-01-02   1_morning           41  12649.35  324.342308

In [39]:
rides_time_series_week = rides.groupby('req_week').agg({
'ride_id': 'count',
'fare_amount': ['sum', 'mean']
}).reset_index()
rides_time_series_week.columns = ['week', 'rides_count', 'gmv', 'avg_fare']
rides_time_series_week.head()

   week  rides_count        gmv    avg_fare
0     1          925  320142.04  356.109055
1     2          884  301781.96  350.501696
2     3          968  337313.28  358.082038
3     4          911  310219.41  352.121918
4     5          951  325373.57  352.517411

In [53]:
import re

In [54]:
def extract_district(address):
    match = re.search (r'Казань,\s+(.+)\s*р-н', address)
    if match:
        return match.group(1).strip()
    return 'Unknown'

In [55]:
rides['district_name'] = rides['pickup_address'].apply(extract_district)

In [57]:
geo_heatmap = rides[rides['status'] == 'completed'].groupby('district_name').agg({
'ride_id': 'count',
'pickup_lat': 'mean',
'pickup_lon': 'mean',
'fare_amount': 'mean'
}).reset_index()
geo_heatmap.columns = ['district', 'rides_count', 'lat', 'lon', 'avg_fare']
geo_heatmap

           district  rides_count        lat        lon    avg_fare
0  Авиастроительный         7170  55.788309  49.121345  358.961933
1       Вахитовский         7276  55.788773  49.120906  353.400803
2  Ново-Савиновский         7383  55.789026  49.121937  357.302228
3       Приволжский         7183  55.788592  49.122067  351.122658
4         Советский         7291  55.788442  49.122133  354.039346
5             Центр         7218  55.788715  49.121748  357.736869

In [58]:
# Соединение данных
union_data = rides.merge(drivers, on = 'driver_id')\
                  .rename (columns = {'registration_date': 'reg_date_drive', 'is_active' : 'active_drive'})
union_data.head()

,ride_id,passenger_id,driver_id,request_time,pickup_time,dropoff_time,pickup_address,dropoff_address,pickup_lat,pickup_lon,...,first_name,last_name,phone,license_number,car_model,car_plate,reg_date_drive,rating_avg,active_drive,shift_preference
0,1,1802,61,2024-07-03 16:51:00,2024-07-03 16:59:00,2024-07-03 17:12:00,"Казань, Ново-Савиновский р-н, ул. Примерная, 153","Казань, Центр р-н, ул. Другая, 163",55.753447,49.150420,...,Андрей,Попов,+79619904272,458419595,Lada Vesta,М202АУ16,2024-02-19,4.36,True,evening
1,2,967,142,2024-08-02 11:28:00,2024-08-02 11:31:00,2024-08-02 11:39:00,"Казань, Советский р-н, ул. Примерная, 167","Казань, Приволжский р-н, ул. Другая, 168",55.809708,49.046326,...,Сергей,Кузнецов,+79415429295,512052311,VW Polo,У402АК16,2024-06-03,4.56,True,evening
2,3,953,69,2024-10-12 18:15:00,2024-10-12 18:19:00,2024-10-12 18:44:00,"Казань, Советский р-н, ул. Примерная, 86","Казань, Центр р-н, ул. Другая, 33",55.835653,49.076059,...,Александр,Петров,+79951078441,497095728,Skoda Rapid,В579АТ16,2024-01-19,4.44,True,night
3,4,812,24,2024-09-12 15:34:00,2024-09-12 15:42:00,2024-09-12 16:02:00,"Казань, Авиастроительный р-н, ул. Примерная, 105","Казань, Приволжский р-н, ул. Другая, 148",55.811017,49.051975,...,Андрей,Смирнов,+79228727266,823521651,Lada Vesta,В529АТ16,2024-06-21,4.67,True,night
4,5,2468,129,2024-01-15 15:44:00,2024-01-15 15:50:00,2024-01-15 16:24:00,"Казань, Ново-Савиновский р-н, ул. Примерная, 37","Казань, Авиастроительный р-н, ул. Другая, 145",55.740437,49.193611,...,Павел,Смирнов,+79926178355,468967256,Lada Vesta,С528АВ16,2024-04-04,4.85,True,evening

In [59]:
driver_stats = union_data[union_data['status'] == 'completed'].groupby('driver_id').agg(
                                            rides_count = ('ride_id', 'count'),
                                            total_earnings = ('fare_amount', 'sum'),          
                                            avg_fare = ('fare_amount', 'mean'),           # avg fare
                                            tot_distance = ('distance_km', 'sum'),  
                                            avg_distance = ('distance_km', 'mean'),          # avg distance
                                            avg_duration = ('duration_minutes', 'mean'),
                                            avg_rating = ('rating_avg', 'mean'),
                                            driver_type = ('shift_preference', 'first')
                                            ).reset_index()
driver_stats.head()

,driver_id,rides_count,total_earnings,avg_fare,tot_distance,avg_distance,avg_duration,avg_rating,driver_type
0,1,303,104828.18,345.967591,1752.11,5.782541,19.712871,4.79,flexible
1,2,304,103425.27,340.214704,1704.61,5.607270,19.144737,4.76,flexible
2,3,312,108724.52,348.476026,1811.46,5.805962,20.112179,4.97,morning
3,4,315,115537.09,366.784413,1977.72,6.278476,21.044444,4.98,night
4,5,287,106638.38,371.562300,1828.23,6.370139,21.372822,4.89,flexible

In [65]:
kpi_daily_2.to_csv('kpi_daily.csv', index=False)
rides_time_series_day.to_csv('rides_time_series.csv', index=False)
geo_heatmap.to_csv('geo_heatmap.csv', index=False)
driver_stats.to_csv('driver_stats.csv', index=False)